"""
Demo seeder — creates a realistic fake completed project in the database
and populates its directory with pre-built files.

This runs once at startup and is idempotent.
"""
from __future__ import annotations

import json
import logging
import math
import random
from datetime import datetime
from pathlib import Path

from backend.config import settings
from backend.models import Project, Job

logger = logging.getLogger("bindcraft.demo")

DEMO_PROJECT_ID = "demo-acetylcholinesterase"
DEMO_JOB_ID = "demo-job-001"


def seed_demo_project() -> None:
    """Insert the demo project if it does not already exist."""
    from backend.database import SessionLocal

    db = SessionLocal()
    try:
        existing = db.query(Project).filter(Project.id == DEMO_PROJECT_ID).first()
        if existing:
            return  # Already seeded

        logger.info("Seeding demo project...")
        _create_files()

        project = Project(
            id=DEMO_PROJECT_ID,
            name="Demo: Acetylcholinesterase + Donepezil",
            notes=(
                "This is a pre-built demonstration project simulating the binding of "
                "donepezil (Aricept) to human acetylcholinesterase — a classic example "
                "in pharmacology education. The data is synthetic but realistic."
            ),
            pdb_filename="ache_donepezil_complex.pdb",
            ligand_filename="donepezil.sdf",
            ligand_name="DPZ",
            ligand_charge=1,
            status="completed",
            settings_json=json.dumps({
                "protein_ff": "ff14SB",
                "ligand_ff": "GAFF2",
                "water_model": "TIP3P",
                "solvent_type": "explicit",
                "box_padding": 10.0,
                "temperature": 300.0,
                "pressure": 1.0,
                "preset": "fast_test",
                "output_freq": 500,
            }),
        )
        db.add(project)

        job = Job(
            id=DEMO_JOB_ID,
            project_id=DEMO_PROJECT_ID,
            mode="run",
            status="success",
            current_step="Complete",
            started_at=datetime(2025, 6, 15, 10, 0, 0),
            finished_at=datetime(2025, 6, 15, 10, 23, 45),
        )
        db.add(job)
        db.commit()
        logger.info("Demo project seeded successfully.")
    except Exception as exc:
        db.rollback()
        logger.error("Failed to seed demo project: %s", exc)
    finally:
        db.close()


def _create_files() -> None:
    """Write all demo data files."""
    base = settings.project_path(DEMO_PROJECT_ID)
    for sub in ("input", "output", "logs", "analysis", "report"):
        (base / sub).mkdir(parents=True, exist_ok=True)

    _write_demo_pdb(base / "input" / "ache_donepezil_complex.pdb")
    _write_demo_sdf(base / "input" / "donepezil.sdf")
    _write_demo_tleap(base / "input")
    _write_demo_mdins(base / "input")
    _write_demo_cpptraj(base / "input")
    _write_demo_mdout(base / "output")
    _write_demo_log(base / "logs" / f"{DEMO_JOB_ID}.log")
    _write_demo_analysis(base / "analysis")
    _write_demo_report(base / "report")


# ── File writers ──────────────────────────────────────────────────────────────

def _write_demo_pdb(path: Path) -> None:
    """Write a minimal but realistic-looking PDB header + a few residues."""
    content = """\
REMARK  1 DEMO: Human Acetylcholinesterase (1EVE) + Donepezil complex
REMARK  2 This is synthetic demo data generated by BindCraft for educational use.
REMARK  3 NOT for research or clinical use.
ATOM      1  N   SER A   1       4.234  12.876   8.234  1.00 20.50           N
ATOM      2  CA  SER A   1       5.112  11.756   8.567  1.00 20.50           C
ATOM      3  C   SER A   1       6.512  12.156   8.900  1.00 20.50           C
ATOM      4  O   SER A   1       6.712  13.349   9.012  1.00 20.50           O
ATOM      5  CB  SER A   1       4.890  10.676   7.534  1.00 20.50           C
ATOM      6  OG  SER A   1       3.567  10.234   7.456  1.00 20.50           O
ATOM      7  H   SER A   1       3.345  12.654   8.123  1.00 20.50           H
ATOM      8  N   TYR A   2       7.456  11.234   9.100  1.00 18.20           N
ATOM      9  CA  TYR A   2       8.834  11.567   9.345  1.00 18.20           C
ATOM     10  C   TYR A   2       9.234  12.890   8.789  1.00 18.20           C
ATOM     11  O   TYR A   2       8.678  13.890   9.012  1.00 18.20           O
ATOM     12  CB  TYR A   2       9.678  10.432  8.890  1.00 18.20           C
ATOM     13  CG  TYR A   2      11.045  10.789  8.678  1.00 18.20           C
ATOM     14  CD1 TYR A   2      11.567  10.234  7.567  1.00 18.20           C
ATOM     15  CD2 TYR A   2      11.890  11.678  9.345  1.00 18.20           C
ATOM     16  CE1 TYR A   2      12.890  10.567  7.456  1.00 18.20           C
ATOM     17  CE2 TYR A   2      13.123  11.890  9.123  1.00 18.20           C
ATOM     18  CZ  TYR A   2      13.678  11.345  8.012  1.00 18.20           C
ATOM     19  OH  TYR A   2      14.890  11.567  7.890  1.00 18.20           O
ATOM     20  H   TYR A   2       7.234  10.456   9.234  1.00 18.20           H
HETATM  500  C1  DPZ A 500       2.134   8.567  15.234  1.00 25.50           C
HETATM  501  C2  DPZ A 500       1.890   7.345  15.890  1.00 25.50           C
HETATM  502  C3  DPZ A 500       2.456   6.234  15.456  1.00 25.50           C
HETATM  503  N1  DPZ A 500       3.234   6.456  14.456  1.00 25.50           N
HETATM  504  C4  DPZ A 500       3.567   7.678  14.234  1.00 25.50           C
HETATM  505  C5  DPZ A 500       2.890   8.678  14.456  1.00 25.50           C
HETATM  506  O1  DPZ A 500       1.234   7.123  17.012  1.00 25.50           O
HETATM  507  O2  DPZ A 500       0.678   5.890  16.234  1.00 25.50           O
HETATM  508  H1  DPZ A 500       1.234   9.456  15.567  1.00 25.50           H
END
"""
    path.write_text(content, encoding="utf-8")


def _write_demo_sdf(path: Path) -> None:
    content = """\

     BindCraft                   3D

 36 38  0  0  1  0  0  0  0  0999 V2000
    2.1340    8.5670   15.2340 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8900    7.3450   15.8900 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.4560    6.2340   15.4560 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.2340    6.4560   14.4560 N   0  0  0  0  0  0  0  0  0  0  0  0
    3.5670    7.6780   14.2340 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.8900    8.6780   14.4560 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2340    7.1230   17.0120 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.6780    5.8900   16.2340 O   0  0  0  0  0  0  0  0  0  0  0  0
M  CHG  1   4   1
M  END
$$$$
"""
    path.write_text(content, encoding="utf-8")


def _write_demo_tleap(input_dir: Path) -> None:
    content = """\
# tleap input generated by BindCraft (DEMO)
# Protein FF: ff14SB | Ligand FF: GAFF2 | Water: TIP3P

source leaprc.protein.ff14SB
source leaprc.gaff2
source leaprc.water.tip3p
loadamberparams DPZ.frcmod
DPZ = loadmol2 DPZ_gaff2.mol2

complex = loadpdb ache_donepezil_complex_clean.pdb
setBox complex vdw 10.0
saveamberparm complex complex.prmtop complex.inpcrd
quit
"""
    (input_dir / "tleap.in").write_text(content, encoding="utf-8")


def _write_demo_mdins(input_dir: Path) -> None:
    (input_dir / "min.mdin").write_text("""\
Minimization — BindCraft Demo
 &cntrl
  imin=1, maxcyc=2000, ncyc=1000,
  ntb=1, ntp=0,
  ntpr=100, ntwr=500,
  cut=10.0,
 /
""", encoding="utf-8")

    (input_dir / "heat.mdin").write_text("""\
Heating NVT 0→300 K — BindCraft Demo
 &cntrl
  imin=0, irest=0, ntx=1,
  nstlim=5000, dt=0.002,
  ntc=2, ntf=2,
  ntb=1, ntp=0,
  tempi=0.0, temp0=300.0,
  ntt=3, gamma_ln=2.0,
  ntpr=500, ntwx=500, ntwr=500,
  cut=10.0,
 /
""", encoding="utf-8")

    (input_dir / "equil.mdin").write_text("""\
Equilibration NPT — BindCraft Demo
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim=10000, dt=0.002,
  ntc=2, ntf=2,
  ntb=2, ntp=1, pres0=1.0, taup=2.0,
  temp0=300.0, ntt=3, gamma_ln=2.0,
  ntpr=500, ntwx=500, ntwr=500,
  cut=10.0,
 /
""", encoding="utf-8")

    (input_dir / "prod.mdin").write_text("""\
Production NPT — BindCraft Demo
 &cntrl
  imin=0, irest=1, ntx=5,
  nstlim=25000, dt=0.002,
  ntc=2, ntf=2,
  ntb=2, ntp=1, pres0=1.0, taup=2.0,
  temp0=300.0, ntt=3, gamma_ln=2.0,
  ntpr=500, ntwx=500, ntwr=500,
  cut=10.0,
 /
""", encoding="utf-8")


def _write_demo_cpptraj(input_dir: Path) -> None:
    (input_dir / "cpptraj.in").write_text("""\
# cpptraj analysis — BindCraft Demo
parm ../input/complex.prmtop
trajin ../output/prod.mdcrd

# Strip water for analysis
strip :WAT,Na+,Cl-

# RMSD protein backbone
rmsd backbone @CA,C,N out rmsd.csv

# RMSF per residue
atomicfluct out rmsf.csv byres

# Radius of gyration
radgyr out rg.csv mass

run
""", encoding="utf-8")


def _write_demo_mdout(output_dir: Path) -> None:
    """Generate a realistic-looking minimal mdout for production stage."""
    lines = [
        "          -------------------------------------------------------",
        "          Amber 22 SANDER                              2022",
        "          -------------------------------------------------------",
        "",
        "| PMEMD implementation of SANDER, Release 22",
        "",
        " NSTEP =    500   TIME(PS) =    1.000  TEMP(K) =  299.8  PRESS =    -24.5",
        " Etot   =   -48234.5678  EKtot   =    9123.4567  EPtot      =   -57358.0245",
        " BOND   =      345.6789  ANGLE   =      567.8901  DIHED      =     1234.5678",
        "",
    ]
    # Generate 50 frames of synthetic data
    for i in range(1, 51):
        nstep = i * 500
        time = i * 1.0
        temp = 300.0 + 2.0 * math.sin(i * 0.3) + random.gauss(0, 0.5)
        eptot = -57000.0 - 200 * math.exp(-i * 0.05) + random.gauss(0, 50)
        lines += [
            f" NSTEP = {nstep:6d}   TIME(PS) = {time:8.3f}  TEMP(K) = {temp:6.2f}  PRESS =   {random.uniform(-50, 50):.1f}",
            f" Etot   = {eptot + 9000:12.4f}  EKtot   =   9134.2345  EPtot      = {eptot:12.4f}",
            f" BOND   =    {random.uniform(300, 400):.4f}  ANGLE   =    {random.uniform(500, 650):.4f}  DIHED      =   {random.uniform(1200, 1300):.4f}",
            "",
        ]
    (output_dir / "prod.mdout").write_text("\n".join(lines), encoding="utf-8")


def _write_demo_log(path: Path) -> None:
    content = """\
[10:00:00] BindCraft Job demo-job-001 | Mode: run | 2025-06-15T10:00:00
[10:00:01] Rendering AMBER input files
[10:00:01] [OK] Rendered tleap.in
[10:00:01] [OK] Rendered min.mdin
[10:00:01] [OK] Rendered heat.mdin
[10:00:01] [OK] Rendered equil.mdin
[10:00:01] [OK] Rendered prod.mdin
[10:00:01] [OK] Rendered cpptraj.in
[10:00:02] Cleaning PDB with pdb4amber
[10:00:05] [OK] pdb4amber complete
[10:00:06] Parameterising ligand with antechamber (GAFF2)
[10:01:45] [OK] antechamber complete — DPZ_gaff2.mol2 written
[10:01:46] Generating missing parameters with parmchk2
[10:01:48] [OK] parmchk2 complete — DPZ.frcmod written
[10:01:49] Building topology with tleap
[10:02:10] [OK] tleap complete — complex.prmtop (45,890 atoms), complex.inpcrd written
[10:02:11] sander: Minimization
[10:05:23] [OK] Minimization complete
[10:05:24] sander: Heating (NVT)
[10:09:45] [OK] Heating complete
[10:09:46] sander: Equilibration (NPT)
[10:15:12] [OK] Equilibration complete
[10:15:13] sander: Production (NPT)
[10:23:44] [OK] Production complete
[10:23:44] Running cpptraj analysis
[10:23:45] [OK] cpptraj analysis complete.

[SUCCESS] BindCraft pipeline complete!
"""
    path.write_text(content, encoding="utf-8")


def _write_demo_analysis(analysis_dir: Path) -> None:
    """Write synthetic but realistic RMSD, RMSF, Rg CSVs."""
    random.seed(42)

    # RMSD — slowly rises then plateaus around 2.5 Å
    with open(analysis_dir / "rmsd.csv", "w") as f:
        f.write("#Frame,RMSD\n")
        for i in range(1, 51):
            rmsd = 2.5 * (1 - math.exp(-i * 0.08)) + random.gauss(0, 0.05)
            f.write(f"{i},{max(0, rmsd):.4f}\n")

    # RMSF — per residue (50 residues)
    with open(analysis_dir / "rmsf.csv", "w") as f:
        f.write("#Residue,RMSF\n")
        for i in range(1, 51):
            # Loop regions have higher RMSF
            base = 0.8 if (10 <= i <= 15 or 35 <= i <= 40) else 0.4
            rmsf = base + random.gauss(0, 0.1)
            f.write(f"{i},{max(0, rmsf):.4f}\n")

    # Rg — radius of gyration, slightly decreasing as system compacts
    with open(analysis_dir / "rg.csv", "w") as f:
        f.write("#Frame,Rg\n")
        for i in range(1, 51):
            rg = 22.5 - 0.5 * (1 - math.exp(-i * 0.06)) + random.gauss(0, 0.1)
            f.write(f"{i},{rg:.4f}\n")


def _write_demo_report(report_dir: Path) -> None:
    html = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BindCraft Demo Report — Acetylcholinesterase + Donepezil</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; color: #333; }
  h1 { color: #5c6bc0; }
  h2 { color: #3949ab; border-bottom: 1px solid #ddd; padding-bottom: 0.3em; margin-top: 2rem; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 1rem; }
  td { padding: 0.4em 0.8em; border: 1px solid #ddd; }
  tr:nth-child(even) { background: #f5f5f5; }
  .disclaimer { background: #fff8e1; border-left: 4px solid #f9a825; padding: 1em; margin: 1rem 0; border-radius: 4px; }
</style>
</head>
<body>
<h1>🔬 BindCraft Demo Reproducibility Report</h1>
<p><strong>System:</strong> Human Acetylcholinesterase (AChE) + Donepezil (Aricept)</p>
<p><strong>Generated:</strong> 2025-06-15 10:23 UTC (demo data)</p>
<div class="disclaimer">
  <strong>⚠️ Educational Disclaimer</strong>
  <p>This is <em>synthetic demo data</em> generated by BindCraft for educational purposes only.
  The trajectory data is not from a real simulation. Results are not validated for
  clinical, publication, or regulatory use.</p>
</div>
<h2>Simulation Parameters</h2>
<table>
  <tr><td><strong>Protein Force Field</strong></td><td>ff14SB</td></tr>
  <tr><td><strong>Ligand Force Field</strong></td><td>GAFF2</td></tr>
  <tr><td><strong>Water Model</strong></td><td>TIP3P</td></tr>
  <tr><td><strong>Solvent</strong></td><td>Explicit (octahedral box)</td></tr>
  <tr><td><strong>Temperature</strong></td><td>300 K</td></tr>
  <tr><td><strong>Pressure</strong></td><td>1.0 atm</td></tr>
  <tr><td><strong>Box Padding</strong></td><td>10.0 Å</td></tr>
  <tr><td><strong>Preset</strong></td><td>Fast Learning Test</td></tr>
</table>
<h2>About This System</h2>
<p>Acetylcholinesterase (AChE) is the enzyme responsible for breaking down the neurotransmitter
acetylcholine. Donepezil is an FDA-approved AChE inhibitor used in Alzheimer's disease treatment.
This system is widely used in B.Pharm and M.Pharm computational pharmacology courses.</p>
</body>
</html>"""
    (report_dir / "index.html").write_text(html, encoding="utf-8")
