"""
Report builder — generates an HTML reproducibility report.
"""
from __future__ import annotations

import platform
import sys
from datetime import datetime
from pathlib import Path

from backend.config import settings
from backend.models import Project
from backend.schemas import ProjectSettings


_DISCLAIMER = """
<div class="disclaimer">
  <strong>⚠️ Educational Disclaimer</strong>
  <p>This simulation was generated by BindCraft for <em>educational purposes only</em>.
  Results are not validated for clinical, publication, or regulatory use.
  BindCraft does not perform docking; the ligand pose was provided by the user.
  No free-energy or MM/GBSA calculations are performed.
  Always consult peer-reviewed literature and expert supervision before drawing
  scientific conclusions from MD simulations.</p>
</div>
"""


def build_report(
    project: Project,
    ps: ProjectSettings,
    rendered_files: dict[str, str],
    report_dir: Path,
) -> Path:
    """Generate report/index.html and return its path."""
    from backend.services.template_engine import PRESETS

    preset = PRESETS.get(ps.preset, PRESETS["fast_test"])
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    sections_html = ""

    # Parameters table
    params = [
        ("Project Name", project.name),
        ("Report Generated", now),
        ("Protein Force Field", ps.protein_ff),
        ("Ligand Force Field", ps.ligand_ff),
        ("Water Model", ps.water_model),
        ("Solvent Type", ps.solvent_type.capitalize()),
        ("Temperature", f"{ps.temperature} K"),
        ("Pressure", f"{ps.pressure} atm"),
        ("Box Padding", f"{ps.box_padding} Å"),
        ("Simulation Preset", preset["label"]),
        ("Preset Description", preset["description"]),
        ("Output Frequency", f"every {ps.output_freq} steps"),
        ("Ligand Residue", project.ligand_name or "auto"),
        ("Ligand Net Charge", str(project.ligand_charge or 0)),
    ]
    rows = "".join(
        f"<tr><td><strong>{k}</strong></td><td>{v}</td></tr>" for k, v in params
    )
    sections_html += f"<h2>Simulation Parameters</h2><table>{rows}</table>"

    # Environment
    env_rows = "".join(
        f"<tr><td><strong>{k}</strong></td><td>{v}</td></tr>"
        for k, v in [
            ("Python", sys.version),
            ("Platform", platform.platform()),
            ("BindCraft Version", settings.version),
            ("AmberTools (configured)", settings.ambertools_bin),
            ("WSL Distro", settings.wsl_distro),
        ]
    )
    sections_html += f"<h2>Environment</h2><table>{env_rows}</table>"

    # Generated files
    file_blocks = ""
    for fname, content in rendered_files.items():
        escaped = content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        file_blocks += f"<h3>{fname}</h3><pre>{escaped}</pre>"
    sections_html += f"<h2>Generated Input Files</h2>{file_blocks}"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BindCraft Reproducibility Report — {project.name}</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; color: #333; }}
  h1 {{ color: #5c6bc0; }}
  h2 {{ color: #3949ab; border-bottom: 1px solid #ddd; padding-bottom: 0.3em; margin-top: 2rem; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 1rem; }}
  td {{ padding: 0.4em 0.8em; border: 1px solid #ddd; }}
  tr:nth-child(even) {{ background: #f5f5f5; }}
  pre {{ background: #1e1e2e; color: #cdd6f4; padding: 1em; border-radius: 6px; overflow-x: auto; font-size: 0.85em; }}
  .disclaimer {{ background: #fff8e1; border-left: 4px solid #f9a825; padding: 1em; margin: 1rem 0; border-radius: 4px; }}
</style>
</head>
<body>
<h1>🔬 BindCraft Reproducibility Report</h1>
<p><strong>Project:</strong> {project.name}</p>
<p><strong>Generated:</strong> {now}</p>
{_DISCLAIMER}
{sections_html}
</body>
</html>"""

    out_path = report_dir / "index.html"
    out_path.write_text(html, encoding="utf-8")
    return out_path
