"""
ZIP builder — packages project files for download.
"""
from __future__ import annotations

import zipfile
from pathlib import Path


def build_zip(project_dir: Path, project_id: str) -> Path:
    """
    Create a ZIP archive of the project directory.
    Returns the path to the created ZIP file.
    """
    zip_path = project_dir / f"bindcraft_{project_id[:8]}.zip"
    categories = ["input", "output", "logs", "analysis", "report"]

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for cat in categories:
            folder = project_dir / cat
            if folder.exists():
                for f in folder.rglob("*"):
                    if f.is_file() and f.suffix not in (".zip",):
                        arcname = f"bindcraft/{cat}/{f.name}"
                        zf.write(f, arcname)

        # Add a top-level README
        readme = _generate_readme(project_id)
        zf.writestr("bindcraft/HOW_TO_REPRODUCE.md", readme)

    return zip_path


def _generate_readme(project_id: str) -> str:
    return f"""# BindCraft Project Package

Project ID: {project_id}

## Contents

- `input/`   — Uploaded files + rendered AMBER input files (tleap.in, *.mdin, cpptraj.in)
- `output/`  — sander output files (*.mdout, *.mdcrd, *.rst7)
- `logs/`    — Job execution logs
- `analysis/`— cpptraj analysis CSVs (rmsd.csv, rmsf.csv, rg.csv)
- `report/`  — HTML reproducibility report

## How to Reproduce

1. Install AmberTools (free) via conda:
   ```
   conda create -n ambertools ambertools -c conda-forge
   conda activate ambertools
   ```
2. Run the commands in the order shown in `report/index.html`.
3. Or re-run from the same BindCraft project using "Run Local" mode.

## Educational Disclaimer

This package was generated by BindCraft for educational purposes only.
Results are not validated for clinical, publication, or regulatory use.
"""
